# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64db2d39e9076869ae08494a3774c26ef3ef6365a55f989c564b010d2001161dd6fc75b664d2523b55d56c65963652be3b772a31305e672806ea6858d8ccbd0b

test:
  secret_key_base: 8ad15ef3495cb30f8a980fdb48dbdc9e3226b7edeb2d6de319f67b45297b4b9c154d7feb52897dbf451531b853d6ae2f8da2898e09732781907ffa82232d8fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
